/**
 * useDirectCallController — composition root for the 1:1 call runtime.
 *
 * This hook does not contain business logic. Its sole responsibility is wiring:
 * it instantiates every runtime sub-hook, threads refs and callbacks between
 * them, and returns the minimal surface consumed by DirectCallPanel.
 *
 * Ownership map:
 *   State & refs      → useDirectCallControllerState
 *   Teardown          → useDirectCallSessionLifecycle (finishCallSession, resetCallState, closePeerConnection)
 *   WebRTC core       → useDirectCallPeerConnectionRuntime
 *   Signaling ingress → useDirectCallSignalRuntime
 *   Negotiation       → useDirectCallNegotiationRuntime
 *   Call setup/accept → useDirectCallSetupControlRuntime
 *   Media controls    → useDirectCallOutgoingMediaState + useDirectCallVisualMediaControls
 *   Presentation      → useDirectCallControllerPresentationWiring → useDirectCallPresentationBindings
 */
import {
  useCallback,
  useEffect,
} from "react";
import { useI18n } from "@/i18n";
import { useMessagesStore } from "@/stores/messages";
import { useSecuritySettings } from "@/ui-settings";
import {
  useDirectCallControllerControlWiring,
  useDirectCallControllerMediaWiring,
  useDirectCallControllerPresentationWiring,
  useDirectCallControllerSessionWiring,
  useDirectCallControllerState,
  useDirectCallControllerTransportWiring,
} from "./controller";
import { useDirectCallDevDebug } from "./debug";
import { useDirectCallRemoteMediaRuntime } from "./media";
import { useDirectCallSignalRuntime } from "./useDirectCallSignalRuntime";
import { useDirectCallNegotiationRuntime } from "./useDirectCallNegotiationRuntime";
import { useDirectCallPeerConnectionRuntime } from "./useDirectCallPeerConnectionRuntime";

export function useDirectCallController() {
  const { t } = useI18n();
  const { callSecurityMode } = useSecuritySettings();
  const ensureConversationUsername = useMessagesStore((state) => state.ensureConversationUsername);
  const {
    sessionState,
    presentationState,
    mediaState,
    transportState,
    negotiationState,
    diagnosticsState,
  } = useDirectCallControllerState();

  const {
    incoming,
    active,
    incomingRef,
    acceptingIncomingCallRef,
    activeRef,
    callChatKindRef,
    commitIncomingState,
    commitActiveState,
    isCurrentActiveCallContext,
    setActiveIfCurrent,
    directCallLifecycleTokenRef,
    outgoingRingingTimeoutRef,
  } = sessionState;

  const {
    notice,
    isMinimized,
    isSecurityCardOpen,
    setNotice,
    setIsMinimized,
    setIsSecurityCardOpen,
    localPreviewShellRef,
    localScreenPreviewShellRef,
    minimizedDockRef,
    incomingOverlayRef,
    activeOverlayRef,
    incomingAcceptButtonRef,
    incomingMinimizedAcceptButtonRef,
    incomingMinimizedSummaryRef,
    activeMinimizedSummaryRef,
    activeHangupButtonRef,
    noticeTimerRef,
    incomingRingtoneRef,
    outgoingRingtoneRef,
    isDraggingMinimizedDock,
    isDraggingLocalPreview,
    isDraggingLocalScreenPreview,
    minimizedDockInlineStyle,
    localPreviewStyle,
    localScreenPreviewStyle,
    startMinimizedDockDrag,
    moveMinimizedDock,
    stopMinimizedDockDrag,
    startLocalPreviewDrag,
    moveLocalPreview,
    stopLocalPreviewDrag,
    isResizingLocalPreview,
    startLocalPreviewResize,
    moveLocalPreviewResize,
    stopLocalPreviewResize,
    startLocalScreenPreviewDrag,
    moveLocalScreenPreview,
    stopLocalScreenPreviewDrag,
    resetMinimizedDockState,
    resetLocalPreviewState,
    resetLocalScreenPreviewState,
  } = presentationState;

  const {
    localVideoRef,
    localScreenPreviewRef,
    remoteCameraPlaybackRef,
    remoteScreenPlaybackRef,
    remoteInboundVideoProgressRef,
    callMediaStateSeqRef,
    localMediaStateRevisionRef,
    remoteMediaStateSeqRef,
    remoteMediaStateRevisionRef,
    lastIncomingMediaStateRef,
    localStreamRef,
    cameraSenderRef,
    cameraTransceiverRef,
    screenShareTrackRef,
    screenShareSenderRef,
    screenShareTransceiverRef,
    localScreenPreviewStreamRef,
    directCallFrameCryptoStateRef,
    directCallSenderFrameHandlesRef,
    directCallReceiverFrameHandlesRef,
    frameModeRecoveryTimerRef,
    frameModeRecoveryAttemptedCallIdRef,
    syncOutgoingVisualMediaStateTrackBindingsRef,
    clearOutgoingMediaStateTrackBindingsRef,
    remoteVideoTrackRefreshTimerRef,
    refreshRemoteVideoTracksFromPeerRef,
  } = mediaState;

  const {
    peerConnectionRef,
    pendingIceCandidatesRef,
    incomingIceCandidatesRef,
    outgoingIceBatchRef,
    disconnectResetTimerRef,
    disconnectRecoveryAttemptedRef,
  } = transportState;

  const {
    outboundMediaEncryptionOfferRef,
    directCallNegotiationRoleRef,
    supportsPeerRenegotiationV1Ref,
    sendRenegotiationOfferRef,
    flushPendingRenegotiationOfferRef,
    negotiationReadyRef,
    makingOfferRef,
    ignoreOfferRef,
    isSettingRemoteAnswerPendingRef,
    renegotiationRevisionRef,
    lastAppliedRemoteRenegotiationRevisionRef,
    pendingLocalRenegotiationRevisionRef,
    pendingRenegotiationReasonRef,
    renegotiationUnsupportedRef,
  } = negotiationState;

  const {
    lastRenegotiationAttemptRef,
    lastSignalingErrorRef,
    callMediaDebugEnabledRef,
    debugCallMedia,
    recordLastRenegotiationAttempt,
    shouldIgnoreUnexpectedPeerSignal,
  } = diagnosticsState;

  const activeCallId = active?.callId ?? null;
  const {
    remoteCameraSlot,
    remoteScreenSlot,
    remoteVideoReady,
    remoteScreenReady,
    remoteCameraUiStatus,
    remoteScreenUiStatus,
    remoteVideoRef,
    remoteScreenVideoRef,
    remoteVideoCompanionRef,
    remoteScreenCompanionRef,
    remoteCameraProbeRef,
    remoteScreenProbeRef,
    remoteAudioRef,
    remoteAudioStreamRef,
    remoteCameraStreamRef,
    remoteScreenStreamRef,
    remoteCameraSlotRef,
    remoteScreenSlotRef,
    remoteReceiverSlotBindingsRef,
    resolveRemoteReceiverSlotSource,
    processIncomingMediaStateHint,
    updateSlotProgress,
    ingestRemoteVideoTrack,
    resetRemoteMediaRuntime,
  } = useDirectCallRemoteMediaRuntime({
    activeCallId,
    peerConnectionRef,
    cameraTransceiverRef,
    screenShareTransceiverRef,
    lastIncomingMediaStateRef,
    debugCallMedia,
  });

  useDirectCallDevDebug({
    activeRef,
    incomingRef,
    peerConnectionRef,
    localStreamRef,
    remoteAudioStreamRef,
    remoteCameraStreamRef,
    remoteScreenStreamRef,
    remoteCameraSlotRef,
    remoteScreenSlotRef,
    remoteReceiverSlotBindingsRef,
    cameraSenderRef,
    screenShareSenderRef,
    cameraTransceiverRef,
    screenShareTransceiverRef,
    callMediaStateSeqRef,
    localMediaStateRevisionRef,
    remoteMediaStateSeqRef,
    remoteMediaStateRevisionRef,
    lastIncomingMediaStateRef,
    directCallNegotiationRoleRef,
    makingOfferRef,
    ignoreOfferRef,
    isSettingRemoteAnswerPendingRef,
    renegotiationRevisionRef,
    pendingLocalRenegotiationRevisionRef,
    pendingRenegotiationReasonRef,
    lastRenegotiationAttemptRef,
    supportsPeerRenegotiationV1Ref,
    renegotiationUnsupportedRef,
    lastSignalingErrorRef,
    negotiationReadyRef,
    remoteVideoReady,
    remoteScreenReady,
    remoteCameraUiStatus,
    remoteScreenUiStatus,
    remoteVideoRef,
    remoteScreenVideoRef,
    remoteCameraProbeRef,
    remoteScreenProbeRef,
    localVideoRef,
    callMediaDebugEnabledRef,
  });
  const {
    flushOutgoingIceBatch,
    resetOutgoingIceBatch,
    enqueueOutgoingIceCandidate,
    getTurnCredentials,
    closeDirectCallFrameCrypto,
    resolveLocalSupportedMediaEncryptionModes,
    ensureDirectCallSenderFrameCryptoBound,
    primeDirectCallSenderFrameCrypto,
    ensureDirectCallReceiverFrameCryptoBound,
    configureDirectCallFrameCrypto,
    prepareLocalEphemeralKey,
    setPeerEphemeralPublicKey,
    ingestRemoteReceiverTrack,
    refreshRemoteVideoTracksFromPeer,
  } = useDirectCallControllerTransportWiring({
    outgoingIceBatchRef,
    frameCrypto: {
      peerConnectionRef,
      cameraSenderRef,
      screenShareSenderRef,
      directCallFrameCryptoStateRef,
      directCallSenderFrameHandlesRef,
      directCallReceiverFrameHandlesRef,
      debugCallMedia,
    },
    remoteReceiverIngress: {
      activeRef,
      peerConnectionRef,
      remoteAudioRef,
      remoteAudioStreamRef,
      remoteVideoTrackRefreshTimerRef,
      refreshRemoteVideoTracksFromPeerRef,
      debugCallMedia,
      isCurrentActiveCallContext,
      ingestRemoteVideoTrack,
      resolveRemoteReceiverSlotSource,
    },
  });
  const {
    resolvePeerLabel,
    recordCallEvent,
    pushNotice,
    finishCallSession,
    resetCallState,
    resetCallStateIfCurrent,
    sendAuthoritativeDirectCallReject,
    applySignalVerificationResult,
    applyCallSecurityState,
  } = useDirectCallControllerSessionWiring({
    activeRef,
    debugCallMedia,
    activeCallId,
    peerSupportsRenegotiationV1: active?.peerSupportsRenegotiationV1,
    supportsPeerRenegotiationV1Ref,
    setIsSecurityCardOpen,
    uiFeedback: {
      setNotice,
      noticeTimerRef,
    },
    sessionLifecycle: {
      active,
      incomingCallId: incoming?.callId ?? null,
      callSecurityMode,
      remoteVideoReady,
      remoteScreenReady,
      remoteCameraSlot,
      remoteScreenSlot,
      remoteCameraStreamRef,
      remoteScreenStreamRef,
      incomingRef,
      acceptingIncomingCallRef,
      activeRef,
      localVideoRef,
      localScreenPreviewRef,
      remoteVideoRef,
      remoteScreenVideoRef,
      remoteCameraProbeRef,
      remoteScreenProbeRef,
      remoteAudioRef,
      remoteCameraPlaybackRef,
      remoteScreenPlaybackRef,
      remoteInboundVideoProgressRef,
      callMediaStateSeqRef,
      localMediaStateRevisionRef,
      remoteMediaStateSeqRef,
      remoteMediaStateRevisionRef,
      lastIncomingMediaStateRef,
      setIncoming: commitIncomingState,
      setActive: commitActiveState,
      setIsMinimized,
      peerConnectionRef,
      localStreamRef,
      cameraSenderRef,
      cameraTransceiverRef,
      screenShareTrackRef,
      screenShareSenderRef,
      screenShareTransceiverRef,
      localScreenPreviewStreamRef,
      remoteAudioStreamRef,
      outgoingIceBatchReset: resetOutgoingIceBatch,
      resetRemoteMediaRuntime,
      closeDirectCallFrameCrypto,
      resetMinimizedDockState,
      resetLocalPreviewState,
      resetLocalScreenPreviewState,
      configureDirectCallFrameCrypto,
      t,
      outboundMediaEncryptionOfferRef,
      pendingIceCandidatesRef,
      incomingIceCandidatesRef,
      frameModeRecoveryTimerRef,
      frameModeRecoveryAttemptedCallIdRef,
      incomingRingtoneRef,
      outgoingRingtoneRef,
      directCallLifecycleTokenRef,
      directCallNegotiationRoleRef,
      supportsPeerRenegotiationV1Ref,
      renegotiationUnsupportedRef,
      negotiationReadyRef,
      makingOfferRef,
      ignoreOfferRef,
      isSettingRemoteAnswerPendingRef,
      renegotiationRevisionRef,
      lastAppliedRemoteRenegotiationRevisionRef,
      pendingLocalRenegotiationRevisionRef,
      pendingRenegotiationReasonRef,
      lastRenegotiationAttemptRef,
      lastSignalingErrorRef,
      disconnectResetTimerRef,
      disconnectRecoveryAttemptedRef,
      clearOutgoingMediaStateTrackBindingsRef,
      isCurrentActiveCallContext,
    },
    securityState: {
      activeRef,
      setActive: commitActiveState,
      t,
    },
  });

  const { createPeerConnection } = useDirectCallPeerConnectionRuntime({
    activeRef,
    peerConnectionRef,
    disconnectResetTimerRef,
    disconnectRecoveryAttemptedRef,
    negotiationReadyRef,
    renegotiationUnsupportedRef,
    sendRenegotiationOfferRef,
    flushPendingRenegotiationOfferRef,
    getTurnCredentials,
    enqueueOutgoingIceCandidate,
    flushOutgoingIceBatch,
    ingestRemoteReceiverTrack,
    isCurrentActiveCallContext,
    setActiveIfCurrent,
    resetCallStateIfCurrent,
    debugCallMedia,
    t,
  });

  const {
    ensureVideoSenders,
    syncVisualTransceiverBindings,
    attachLocalTracksToPeer,
    syncVisualTransceiverDirections,
    requestLocalStream,
    syncLocalPreview,
    syncLocalScreenPreview,
    hasRenderableRemoteCamera,
    hasRenderableRemoteScreen,
    hasRemoteVisualMedia,
    isVideoCallActive,
    shouldRenderLocalCameraPreview,
    localSupportsFrameEncryption,
  } = useDirectCallControllerMediaWiring({
    localMedia: {
      peerConnectionRef,
      cameraTransceiverRef,
      screenShareTransceiverRef,
      cameraSenderRef,
      screenShareSenderRef,
      localStreamRef,
      screenShareTrackRef,
      localVideoRef,
      localScreenPreviewRef,
      localScreenPreviewStreamRef,
      remoteReceiverSlotBindingsRef,
      debugCallMedia,
    },
    resolveLocalSupportedMediaEncryptionModes,
    visualStateSummary: {
      active,
      localStream: localStreamRef.current,
      remoteCameraSlot,
      remoteScreenSlot,
    },
    remoteTelemetry: {
      activeCallId,
      activeRef,
      peerConnectionRef,
      localStreamRef,
      cameraSenderRef,
      screenShareSenderRef,
      remoteInboundVideoProgressRef,
      remoteCameraSlotRef,
      remoteScreenSlotRef,
      remoteCameraProbeRef,
      remoteScreenProbeRef,
      remoteCameraPlaybackRef,
      remoteScreenPlaybackRef,
      debugCallMedia,
      updateSlotProgress,
    },
    mediaElementBindings: {
      activeCallId,
      isMinimized,
      remoteVideoReady,
      remoteScreenReady,
      localVideoRef,
      localScreenPreviewRef,
      remoteVideoRef,
      remoteVideoCompanionRef,
      remoteScreenVideoRef,
      remoteScreenCompanionRef,
      remoteCameraProbeRef,
      remoteScreenProbeRef,
      remoteAudioRef,
      localStreamRef,
      localScreenPreviewStreamRef,
      remoteAudioStreamRef,
      remoteCameraStreamRef,
      remoteScreenStreamRef,
      remoteCameraSlotStream: remoteCameraSlot.stream,
      remoteCameraSlotTrackId: remoteCameraSlot.trackId,
      remoteScreenSlotStream: remoteScreenSlot.stream,
      remoteScreenSlotTrackId: remoteScreenSlot.trackId,
      refreshRemoteVideoTracksFromPeer,
    },
  });

  // Stable ref-forwarding callbacks. These are intentionally created with empty deps —
  // the refs themselves are stable objects whose .current is updated via useEffect below.
  const stableSyncOutgoing = useCallback((callIdOverride?: string) => {
    syncOutgoingVisualMediaStateTrackBindingsRef.current(callIdOverride);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const stableRefreshRemote = useCallback((callIdOverride?: string, reason?: string) => {
    refreshRemoteVideoTracksFromPeerRef.current(callIdOverride, reason);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const clearNotice = useCallback(() => setNotice(null), [setNotice]);

  const {
    sendRenegotiationOffer,
    flushPendingRenegotiationOffer,
    handleIncomingRenegotiationAnswer,
    handleIncomingRenegotiationOffer,
    handleRemoteAnswer,
  } = useDirectCallNegotiationRuntime({
    activeRef,
    peerConnectionRef,
    supportsPeerRenegotiationV1Ref,
    renegotiationUnsupportedRef,
    pendingRenegotiationReasonRef,
    makingOfferRef,
    ignoreOfferRef,
    isSettingRemoteAnswerPendingRef,
    renegotiationRevisionRef,
    lastAppliedRemoteRenegotiationRevisionRef,
    pendingLocalRenegotiationRevisionRef,
    directCallNegotiationRoleRef,
    negotiationReadyRef,
    lastRenegotiationAttemptRef,
    lastSignalingErrorRef,
    outboundMediaEncryptionOfferRef,
    pendingIceCandidatesRef,
    setActive: commitActiveState,
    callSecurityMode,
    debugCallMedia,
    recordLastRenegotiationAttempt,
    shouldIgnoreUnexpectedPeerSignal,
    isCurrentActiveCallContext,
    resetCallState,
    resetCallStateIfCurrent,
    syncVisualTransceiverBindings,
    syncVisualTransceiverDirections,
    syncOutgoingVisualMediaStateTrackBindings: stableSyncOutgoing,
    refreshRemoteVideoTracksFromPeer: stableRefreshRemote,
    configureDirectCallFrameCrypto,
    setPeerEphemeralPublicKey,
    applySignalVerificationResult,
    applyCallSecurityState,
    setActiveIfCurrent,
    pushNotice,
    t,
  });

  useEffect(() => {
    sendRenegotiationOfferRef.current = sendRenegotiationOffer;
  }, [sendRenegotiationOffer, sendRenegotiationOfferRef]);

  useEffect(() => {
    flushPendingRenegotiationOfferRef.current = flushPendingRenegotiationOffer;
  }, [flushPendingRenegotiationOffer, flushPendingRenegotiationOfferRef]);

  const mediaControlsOptions = {
    activeRef,
    localStreamRef,
    peerConnectionRef,
    cameraTransceiverRef,
    cameraSenderRef,
    screenShareTrackRef,
    screenShareSenderRef,
    screenShareTransceiverRef,
    callMediaStateSeqRef,
    localMediaStateRevisionRef,
    negotiationReadyRef,
    renegotiationUnsupportedRef,
    lastSignalingErrorRef,
    callSecurityMode,
    debugCallMedia,
    recordLastRenegotiationAttempt,
    sendRenegotiationOffer,
    setActiveIfCurrent,
    isCurrentActiveCallContext,
    ensureVideoSenders,
    syncVisualTransceiverBindings,
    syncVisualTransceiverDirections,
    syncLocalPreview,
    syncLocalScreenPreview,
    ensureDirectCallSenderFrameCryptoBound,
    configureDirectCallFrameCrypto,
    resetCallState,
    pushNotice,
    t,
  };

  const {
    startCall,
    acceptCall,
    rejectCall,
    hangup,
    sendCallMediaState,
    syncOutgoingVisualMediaStateTrackBindings,
    clearOutgoingMediaStateTrackBindings,
    canSwitchCamera,
    isSwitchingCamera,
    switchCamera,
    toggleVideo,
    toggleScreenShare,
    selectedScreenResolution,
    handleSelectScreenResolution,
    toggleMute,
  } = useDirectCallControllerControlWiring({
    setupControl: {
      activeRef,
      incomingRef,
      acceptingIncomingCallRef,
      peerConnectionRef,
      directCallLifecycleTokenRef,
      outgoingRingingTimeoutRef,
      directCallNegotiationRoleRef,
      supportsPeerRenegotiationV1Ref,
      renegotiationUnsupportedRef,
      negotiationReadyRef,
      makingOfferRef,
      ignoreOfferRef,
      isSettingRemoteAnswerPendingRef,
      renegotiationRevisionRef,
      lastAppliedRemoteRenegotiationRevisionRef,
      pendingLocalRenegotiationRevisionRef,
      pendingIceCandidatesRef,
      incomingIceCandidatesRef,
      outboundMediaEncryptionOfferRef,
      commitIncomingState,
      commitActiveState,
      setIsMinimized,
      resetMinimizedDockState,
      clearNotice,
      callSecurityMode,
      ensureConversationUsername,
      resolvePeerLabel,
      pushNotice,
      callChatKindRef,
      recordCallEvent,
      debugCallMedia,
      createPeerConnection,
      ensureVideoSenders,
      requestLocalStream,
      attachLocalTracksToPeer,
      syncVisualTransceiverBindings,
      syncVisualTransceiverDirections,
      syncOutgoingVisualMediaStateTrackBindings: stableSyncOutgoing,
      refreshRemoteVideoTracksFromPeer: stableRefreshRemote,
      resolveLocalSupportedMediaEncryptionModes,
      primeDirectCallSenderFrameCrypto,
      closeDirectCallFrameCrypto,
      configureDirectCallFrameCrypto,
      prepareLocalEphemeralKey,
      setPeerEphemeralPublicKey,
      applyCallSecurityState,
      finishCallSession,
      t,
    },
    outgoingMediaState: mediaControlsOptions,
    visualMediaControls: {
      active,
      ...mediaControlsOptions,
    },
    activeRef,
    localStreamRef,
    setActiveIfCurrent,
  });

  useEffect(() => {
    syncOutgoingVisualMediaStateTrackBindingsRef.current = syncOutgoingVisualMediaStateTrackBindings;
  }, [syncOutgoingVisualMediaStateTrackBindings, syncOutgoingVisualMediaStateTrackBindingsRef]);

  useEffect(() => {
    clearOutgoingMediaStateTrackBindingsRef.current = clearOutgoingMediaStateTrackBindings;
  }, [clearOutgoingMediaStateTrackBindings, clearOutgoingMediaStateTrackBindingsRef]);


  useDirectCallSignalRuntime({
    activeRef,
    incomingRef,
    acceptingIncomingCallRef,
    peerConnectionRef,
    incomingIceCandidatesRef,
    pendingIceCandidatesRef,
    ignoreOfferRef,
    supportsPeerRenegotiationV1Ref,
    renegotiationUnsupportedRef,
    lastSignalingErrorRef,
    lastRenegotiationAttemptRef,
    remoteMediaStateSeqRef,
    remoteMediaStateRevisionRef,
    lastIncomingMediaStateRef,
    remoteCameraSlotRef,
    remoteScreenSlotRef,
    setActive: commitActiveState,
    setIncoming: commitIncomingState,
    setIsMinimized,
    ensureConversationUsername,
    resetMinimizedDockState,
    resolvePeerLabel,
    pushNotice,
    callChatKindRef,
    recordCallEvent,
    rejectIncomingCall: (callId) => {
      void sendAuthoritativeDirectCallReject(callId);
    },
    finishCallSession,
    debugCallMedia,
    shouldIgnoreUnexpectedPeerSignal,
    processIncomingMediaStateHint,
    handleRemoteAnswer,
    handleIncomingRenegotiationOffer,
    handleIncomingRenegotiationAnswer,
    t,
  });

  const {
    surface,
    focusTrapProps,
    surfaceRendererProps,
  } = useDirectCallControllerPresentationWiring({
    active,
    incoming,
    notice,
    isMinimized,
    isSecurityCardOpen,
    localSupportsFrameEncryption,
    callSecurityMode,
    resolvePeerLabel,
    t,
    incomingOverlayRef,
    activeOverlayRef,
    minimizedDockRef,
    incomingAcceptButtonRef,
    activeHangupButtonRef,
    incomingMinimizedAcceptButtonRef,
    incomingMinimizedSummaryRef,
    activeMinimizedSummaryRef,
    remoteAudioRef,
    remoteCameraProbeRef,
    remoteScreenProbeRef,
    localPreviewShellRef,
    localScreenPreviewShellRef,
    localVideoRef,
    localScreenPreviewRef,
    isDraggingMinimizedDock,
    minimizedDockInlineStyle,
    isDraggingLocalPreview,
    isResizingLocalPreview,
    isDraggingLocalScreenPreview,
    localPreviewStyle,
    localScreenPreviewStyle,
    shouldRenderLocalCameraPreview,
    hasRemoteVisualMedia,
    hasRenderableRemoteCamera,
    hasRenderableRemoteScreen,
    remoteScreenStream: remoteScreenSlot.stream,
    remoteVideoRef,
    remoteVideoCompanionRef,
    remoteScreenVideoRef,
    remoteScreenCompanionRef,
    localStream: localStreamRef.current,
    cameraSenderRef,
    canSwitchCamera,
    isSwitchingCamera,
    selectedScreenResolution,
    setIsMinimized,
    setIsSecurityCardOpen,
    rejectCall,
    acceptCall,
    toggleMute,
    hangup,
    switchCamera,
    toggleVideo,
    toggleScreenShare,
    handleSelectScreenResolution,
    startMinimizedDockDrag,
    moveMinimizedDock,
    stopMinimizedDockDrag,
    startLocalPreviewDrag,
    moveLocalPreview,
    stopLocalPreviewDrag,
    startLocalPreviewResize,
    moveLocalPreviewResize,
    stopLocalPreviewResize,
    startLocalScreenPreviewDrag,
    moveLocalScreenPreview,
    stopLocalScreenPreviewDrag,
  });

  return {
    startCall,
    surface,
    notice,
    focusTrapProps,
    surfaceRendererProps,
  };
}
